### ISSUE TITLE
problem with Danish letters

### ISSUE THREAD

**Issue by helmuthm** [php-fusion/PHP-Fusion-8-Locales#2]
when updating files containing the Danish letters Æ, æ, Ø, ø, Å, å they show up as something else ...

how to solve this?

**Comment by RobiNN1** [comment]
Here is reason
![screen](https://user-images.githubusercontent.com/11664877/50542273-e6c47200-0bb9-11e9-950c-dcb798b3a89b.png)

Check all files again and replace ? to correct chars
I converted all locales to UTF-8.
