### ISSUE TITLE
missing closing tag? ...  and more tags

### ISSUE THREAD

**Issue by helmuthm** [php-fusion/PHP-Fusion-8-Locales#3]
In some of the files the closing tag for php is missing ... should it be inserted?

and what about `<em>` ... convert to `<strong>`?

and `<br />` ... convert to `<br/>`?

**Comment by WuChEn** [comment]
I have All ?> remove from germany locale.
They are Not longer needed. 
Phpf8 Now is utf-8, so you can use all html Tags without escaping. <br /> is Now <br>
<em></em> is kursive and <strong></strong> is big text. Greatz
