### ISSUE TITLE
Charset in Danish locales

### ISSUE THREAD

**Issue by Mivalpuff** [php-fusion/PHP-Fusion-8-Locales#7]
(edit: I managed to post this before finishing)

The setup-local has the following entry:
$locale['charset'] = "uft8";

Making this utf-8 fixed the messy Danish letters for the setup. However, when entering the site, the letters are still messed up. In V7, I fixed this by forcing iso-8859-1 - but as V8 seems to prefer UTF-8, I guess the following in the global locale is an error too:
$locale['charset'] = "iso-8859-1";

**Comment by RobiNN1** [comment]
what?

**Comment by Mivalpuff** [comment]
Sorry, I managed to hit enter too early :)

**Comment by RobiNN1** [comment]
@helmuthm  
https://github.com/php-fusion/PHP-Fusion-8-Locales/blob/master/Danish/locale/Danish/global.php#L20

change iso-8859-1 to utf-8

**Comment by Mivalpuff** [comment]
I see that the global.php locale is also still ANSI. Changing it to UTF-8 fixed some of the issues, but some characters have already been messed up in the file.

**Comment by RobiNN1** [comment]
Wait to @helmuthm , he is from Danish NSS

**Comment by helmuthm** [comment]
changed as proposed [https://github.com/php-fusion/PHP-Fusion-8-Locales/issues/7#issuecomment-451654578]
