### ISSUE TITLE
Danish locale global.php: "Use of undefined constant SITE_EMAIL"

### ISSUE THREAD

**Issue by Mivalpuff** [php-fusion/PHP-Fusion-8-Locales#8]
https://github.com/php-fusion/PHP-Fusion-8-Locales/blob/master/Danish/locale/Danish/global.php#L295

I get this error:
"Use of undefined constant SITE_EMAIL - assumed 'SITE_EMAIL' Linje: 295"

I see that other locales use $settings['siteemail'], and it fixed the error for me.

**Comment by RobiNN1** [comment]
https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=39508&pid=205784#post_205784

**Comment by Mivalpuff** [comment]
Thanks. I'll look there in the future. :)
